# pod-reader-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # The core Kubernetes API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"] # Allows read-only access to pods
