# pod-reader-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
subjects:
- kind: ServiceAccount
  name: pod-reader-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ""
