# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-with-init
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      initContainers:
      - name: init-db
        image: busybox:1.36.1 # Lightweight image for init container
        command: ["sh", "-c", "echo 'Initializing database... (simulating 10s delay)'; sleep 10; echo 'Database initialized.'"]
      containers:
      - name: main-app
        image: nginx:alpine # Main web app container
        ports:
        - containerPort: 80
        # No readiness probe here initially
